// Generated by React Router

import 'react-router'

declare module 'react-router' {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  '/': {
    params: {}
  }
  '/products': {
    params: {}
  }
  '/payment': {
    params: {}
  }
  '/return': {
    params: {}
  }
}

type RouteFiles = {
  'root.tsx': {
    id: 'root'
    page: '/' | '/products' | '/payment' | '/return'
  }
  './layouts/header.tsx': {
    id: 'layouts/header'
    page: '/' | '/products' | '/payment' | '/return'
  }
  'routes/home.tsx': {
    id: 'routes/home'
    page: '/'
  }
  'routes/products.tsx': {
    id: 'routes/products'
    page: '/products'
  }
  'routes/payment.tsx': {
    id: 'routes/payment'
    page: '/payment'
  }
  'routes/return.tsx': {
    id: 'routes/return'
    page: '/return'
  }
}
