// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/product:id": {
    params: {};
  };
  "/payment": {
    params: {};
  };
  "/return": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/product:id" | "/payment" | "/return";
  };
  "./layouts/header.tsx": {
    id: "layouts/header";
    page: "/" | "/products" | "/product:id" | "/payment" | "/return";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/product.tsx": {
    id: "routes/product";
    page: "/product:id";
  };
  "routes/payment.tsx": {
    id: "routes/payment";
    page: "/payment";
  };
  "routes/return.tsx": {
    id: "routes/return";
    page: "/return";
  };
};